import { readable } from "svelte/store";

export const headings = {
	0: "Topic",
	1: "Accounting Metric",
	2: "Units",
	3: "2019",
	4: "2020",
	5: "2021",
	6: "SASB Code<sup class='ml-[1px] lowercase'>(a)</sup>",
	7: "GRI Code<sup class='ml-[1px] lowercase'>(b)</sup>",
	8: "EIC/GPA<sup class='ml-[1px] lowercase'>(c)</sup>",
};

export const array = [
	{
		"2019": "26,028",
		"2020": "33,123",
		"2021": "31,348",
		"topic": "Greenhouse Gas (GHG) Emissions",
		"metric": "Total gross scope 1 emissions (direct GHG emissions)",
		"units": "metric tons (t) CO2-e",
		"sasb_code": "EM-MD-110a.1",
		"gri_code": "305-1 / 11.1.5",
		"eic": "2.4.1",
	},
	{
		"2019": "25,771",
		"2020": "32,838",
		"2021": "31,057",
		"topic": "",
		"metric": "Total scope 1 CO2 emissions</span>",
		"units": "metric tons (t)",
		"sasb_code": "EM-MD-110a.1",
		"gri_code": "305-1 / 11.1.5",
		"eic": "2.4.1.1",
	},
	{
		"2019": 15.8,
		"2020": 19.6,
		"2021": 19.6,
		"topic": "",
		"metric": "Total scope 1 methane emissions",
		"units": "metric tons (t) CO2-e",
		"sasb_code": "EM-MD-110a.1",
		"gri_code": "305-1 / 11.1.5",
		"eic": "2.4.1.2",
	},
	{
		"2019": "0.06%",
		"2020": "0.06%",
		"2021": "0.06%",
		"topic": "",
		"metric": "Percentage methane",
		"units": "percentage (%)",
		"sasb_code": "EM-MD-110a.1",
		"gri_code": "305-1 / 11.1.5",
		"eic": "2.4.1.4",
	},
	{
		"2019": "12.39%",
		"2020": "8.19%",
		"2021": "6.45%",
		"topic": "",
		"metric":
			"Percentage of scope 1 emissions covered under emissions-limiting regulations",
		"units": "percentage (%)",
		"sasb_code": "EM-MD-110a.1",
		"gri_code": "305-1 / 11.1.5",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "6,720",
		"2020": "8,785",
		"2021": "8,984",
		"topic": "",
		"metric": "Total gross location-based Scope 2 GHG emissions",
		"units": "metric tons (t) CO2-e",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "305-2 / 11.1.6",
		"eic": "2.4.3",
	},
	{
		"2019": "32,748",
		"2020": "41,908",
		"2021": "40,332",
		"topic": "",
		"metric": "Total GHG emissions (scope 1 + scope 2)",
		"units": "metric tons (t) CO2-e",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": 2.4,
	},
	{
		"2019": 0.001,
		"2020": 0.001,
		"2021": 0.0005,
		"topic": "",
		"metric":
			"Scope 1 and 2 emission intensity<sup class='inline-block ml-[1px] text-7'>[1]</sup>",
		"units": "metric tons (t) CO2-e per BOE throughput",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "305-4 / 11.1.8",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 639,
		"2020": 793,
		"2021": 809,
		"topic": "",
		"metric":
			"Scope 3 GHG emissions<sup class='inline-block ml-[1px] text-7'>[2]</sup>",
		"units": "metric tons (t) CO2-e",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "305-3 / 11.1.7",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "operational",
		"2020": "operational",
		"2021": "operational",
		"topic": "",
		"metric": "Carbon accounting basis for data",
		"units": "operational / equity / financial",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": 1.4,
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "yes",
		"2021": "yes",
		"topic": "",
		"metric":
			"Does the company have a greenhouse gas emissions reduction target?",
		"units": "yes / no",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": 2.8,
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "environment /  climate change section",
		"topic": "",
		"metric":
			"Discussion of long-term and short-term strategy or plan to manage Scope 1 emissions, emissions reduction targets, and an analysis of performance against those targets.",
		"units": "n/a",
		"sasb_code": "EM-MD-110a.2",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "502,477",
		"2020": "668,700",
		"2021": "613,620",
		"topic": "Energy Management",
		"metric": "Total energy consumed",
		"units": "gigajoules (GJ)",
		"sasb_code": "RT-CH-130a.1",
		"gri_code": "302-1 / 11.1.2",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "32,356,731",
		"2020": "40,698,464",
		"2021": "80,279,425",
		"topic": "",
		"metric":
			"Gross energy throughput converted to barrel of oil equivalents (BOE)",
		"units": "BOE",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": 1.2,
	},
	{
		"2019": "100%",
		"2020": "100%",
		"2021": "100%",
		"topic": "",
		"metric": "Percentage grid electricity",
		"units": "percentage (%)",
		"sasb_code": "RT-CH-130a.1",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "0%",
		"2020": "0%",
		"2021": "0%",
		"topic": "",
		"metric": "Percentage renewable",
		"units": "percentage (%)",
		"sasb_code": "RT-CH-130a.1",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": 2.13,
	},
	{
		"2019": 0,
		"2020": 0,
		"2021": 0,
		"topic": "",
		"metric": "Total self-generated energy",
		"units": "gigajoules (GJ)",
		"sasb_code": "RT-CH-130a.1",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "energy management section",
		"topic": "",
		"metric":
			"Discuss efforts to reduce energy consumption and/or improve energy efficiency.",
		"units": "n/a",
		"sasb_code": "RT-CH-130a.1",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 52,
		"2020": 32.5,
		"2021": 35.4,
		"topic": "Air Quality",
		"metric": "Nitrogen oxides (NO<sub>x</sub>) - air emissions",
		"units": "metric tons (t)",
		"sasb_code": "EM-MD-120a.1",
		"gri_code": "305-7 / 11.3.2",
		"eic": 2.9,
	},
	{
		"2019": 0.2,
		"2020": 32.6,
		"2021": 32.6,
		"topic": "",
		"metric": "Sulfur oxides (SO<sub>x</sub>) - air emissions",
		"units": "metric tons (t)",
		"sasb_code": "EM-MD-120a.1",
		"gri_code": "305-7 / 11.3.2",
		"eic": 2.1,
	},
	{
		"2019": 287,
		"2020": 241.3,
		"2021": 316.5,
		"topic": "",
		"metric": "Volatile Organic Compounds (VOC) - air emissions",
		"units": "metric tons (t)",
		"sasb_code": "EM-MD-120a.1",
		"gri_code": "305-7 / 11.3.2",
		"eic": 2.11,
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": 17.2,
		"2021": 17.3,
		"topic": "",
		"metric": "Particulate Matter (PM<sub>10</sub>) - air emissions",
		"units": "metric tons (t)",
		"sasb_code": "EM-MD-120a.1",
		"gri_code": "305-7 / 11.3.2",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "<span class='text-[9]'>environmental management section</span>",
		"topic": "Ecological Impacts",
		"metric":
			"Description of environmental management policies and practices for active operations",
		"units": "n/a",
		"sasb_code": "EM-MD-160a.1",
		"gri_code": "3-3 / 11.4.1",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "1%",
		"topic": "",
		"metric":
			"Percentage of land operated within or near areas of protected conservation status or endangered species habitat, based on acreage where we have active operations",
		"units": "percentage&nbsp;(%) by&nbsp;acreage",
		"sasb_code": "EM-MD-160a.2",
		"gri_code": "304-1 / 11.4.2\n304-4 / 11.4.5",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "0.6&nbsp;acres<sup class='inline-block ml-[1px] text-8'>[3]</sup>",
		"topic": "",
		"metric": "Terrestrial acreage disturbed",
		"units": "acres (ac)",
		"sasb_code": "EM-MD-160a.3",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "100% <sup class='inline-block ml-[1px] text-8'>[3]</sup>",
		"topic": "",
		"metric": "Percentage of impacted area restored",
		"units": "percentage (%)",
		"sasb_code": "EM-MD-160a.3",
		"gri_code": "304-3 / 11.4.4",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 6,
		"2020": 1,
		"2021": 3,
		"topic": "",
		"metric": "Number of hydrocarbon spills",
		"units": "number",
		"sasb_code": "EM-MD-160a.4",
		"gri_code": "306-3 / 11.8.2",
		"eic": 2.1,
	},
	{
		"2019": "unknown",
		"2020": 40,
		"2021": 19,
		"topic": "",
		"metric": "Aggregate volume of hydrocarbon spills",
		"units": "barrels<br>(bbls)",
		"sasb_code": "EM-MD-160a.4",
		"gri_code": "306-3 / 11.8.2",
		"eic": 2.2,
	},
	{
		"2019": "unknown",
		"2020": 20,
		"2021": 9.5,
		"topic": "",
		"metric": "Volume recovered",
		"units": "barrels<br>(bbls)",
		"sasb_code": "EM-MD-160a.4",
		"gri_code": "306-3 / 11.8.3",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "n/a",
		"2020": "n/a",
		"2021": "n/a",
		"topic": "",
		"metric": "Aggregate volume of hydrocarbon spills in artic",
		"units": "barrels<br>(bbls)",
		"sasb_code": "EM-MD-160a.4",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 0,
		"2020": 0,
		"2021": 0,
		"topic": "",
		"metric":
			"Aggregate volume of hydrocarbon spills in unusually densitive areas (USAs)",
		"units": "barrels<br>(bbls)",
		"sasb_code": "EM-MD-160a.4",
		"gri_code": "306-3 / 11.8.2",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "Zero (0)",
		"topic": "Competitive Behavior",
		"metric":
			"Total amount of monetary losses as a result of legal proceedings associated with federal pipeline and storage regulations<br>&nbsp;",
		"units": "US dollars ($)",
		"sasb_code": "EM-MD-520a.1",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 0,
		"2020": 0,
		"2021": 1,
		"topic": "Safety, Emergency Preparedness & Response",
		"metric": "Number of reportable pipeline incidents",
		"units": "number",
		"sasb_code": "EM-MD-540a.1",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 0,
		"2020": 0,
		"2021": 0,
		"topic": "",
		"metric": "Percentage of significant reportable pipeline incidents",
		"units": "percentage (%)",
		"sasb_code": "EM-MD-540a.1",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "n/a",
		"2020": "n/a",
		"2021": "n/a",
		"topic": "",
		"metric": "Percentage of natural gas pipelines inspected",
		"units": "percentage (%)",
		"sasb_code": "EM-MD-540a.2",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "50%",
		"2020": 0,
		"2021": "23%",
		"topic": "",
		"metric": "Percentage of hazardous liquid pipelines inspected",
		"units": "percentage (%)",
		"sasb_code": "EM-MD-540a.2",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "health, safety, environment & quality section",
		"topic": "",
		"metric":
			"Discussion of management systems used to integrate a culture of safety and emergency preparedness throughout the value chain and throughout project lifecycles",
		"units": "n/a",
		"sasb_code": "EM-MD-540a.4",
		"gri_code": "403-1 / 11.9.2",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 0,
		"2020": 0,
		"2021": 0,
		"topic": "Rail Safety",
		"metric": "Number of accident releases from Rail transportation",
		"units": "number",
		"sasb_code": "EM-MD-540a.3",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 0,
		"2020": 0,
		"2021": 0,
		"topic": "",
		"metric": "Number of non-accident releases (NARs) from Rail transportation",
		"units": "number",
		"sasb_code": "EM-MD-540a.3",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 0.32,
		"2020": 1.1,
		"2021": 1.55,
		"topic": "Workforce Health & Safety",
		"metric":
			"Total recordable incident rate (TRIR) (employees and all contractors)",
		"units": "rate",
		"sasb_code": "EM-EP-320a.1",
		"gri_code": "403-9 / 11.9.10",
		"eic": "3.1\n3.2",
	},
	{
		"2019": 1,
		"2020": 3,
		"2021": 4,
		"topic": "",
		"metric": "Total recordable incidents (employees and all contractors)",
		"units": "number",
		"sasb_code": "EM-EP-320a.1",
		"gri_code": "403-9 / 11.9.10",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 0,
		"2020": 0,
		"2021": 0,
		"topic": "",
		"metric": "Fatality rate",
		"units": "rate",
		"sasb_code": "EM-EP-320a.1",
		"gri_code": "403-9 / 11.9.10",
		"eic": "3.7\n3.8",
	},
	{
		"2019": 1.92,
		"2020": 1.83,
		"2021": 2.33,
		"topic": "",
		"metric": "Near miss frequency rate (NMFR)",
		"units": "rate",
		"sasb_code": "EM-EP-320a.1",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 18,
		"2020": 4,
		"2021": 20,
		"topic": "",
		"metric":
			"Average hours of health, safety, and emergency response training for full-time employees calculated as: (total qualifying training hours provided) / (total number of employees).",
		"units": "hours",
		"sasb_code": "EM-EP-320a.1",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "n/a",
		"2020": 93.8,
		"2021": 89.9,
		"topic": "",
		"metric": "Incident composite rate (goal is 90)",
		"units": "rate",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 0,
		"2020": 1,
		"2021": 2,
		"topic": "",
		"metric": "Restricted work cases",
		"units": "number",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "403-9 / 11.9.10",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 0,
		"2020": 0,
		"2021": 0,
		"topic": "",
		"metric": "Lost time cases",
		"units": "number",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "403-9 / 11.9.10",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": 740,
		"2020": "1,105",
		"2021": "1,470",
		"topic": "",
		"metric":
			"Days since lost time accident (employees and terminal contractors)",
		"units": "Days",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "14%",
		"topic": "Employee Performance",
		"metric": "Voluntary employee turnover rate, U.S.<div>&nbsp;</div>",
		"units": "%",
		"sasb_code": "CG-EC-330a.2",
		"gri_code": "401-1 / 11.10.2",
		"eic": "4.16.1",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "7%",
		"topic": "",
		"metric": "Involuntary employee turnover rate, U.S<div>&nbsp;</div>",
		"units": "%",
		"sasb_code": "CG-EC-330a.2",
		"gri_code": "401-1 / 11.10.2",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "21%",
		"topic": "",
		"metric": "Employee turnover - total<div>&nbsp;</div><div>&nbsp;</div>",
		"units": "%",
		"sasb_code": "CG-EC-330a.2",
		"gri_code": "401-1 / 11.10.2",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "42%",
		"topic": "Employee Demographics",
		"metric":
			"Percentage of female representation in Executive Team management, U.S. workforce",
		"units": "%",
		"sasb_code": "CG-EC-330a.3",
		"gri_code": "405-1 / 11.11.5",
		"eic": 4.2,
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "33%",
		"topic": "",
		"metric": "Percentage of employees age 30-50 in positions of VP or above",
		"units": "%",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "405-1 / 11.11.5",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "67%",
		"topic": "",
		"metric": "Percentage of employees age 50+ in positions of VP or above",
		"units": "%",
		"sasb_code": "<span class='opacity-40'>-</span>",
		"gri_code": "405-1 / 11.11.5",
		"eic": "<span class='opacity-40'>-</span>",
	},
	{
		"2019": "<span class='opacity-40'>-</span>",
		"2020": "<span class='opacity-40'>-</span>",
		"2021": "28%",
		"topic": "",
		"metric": "Percentage of minorities in the U.S. workforce",
		"units": "%",
		"sasb_code": "CG-EC-330a.3",
		"gri_code": "405-1 / 11.11.5",
		"eic": 3.11,
	},
	{
		"2019": 160,
		"2020": 195,
		"2021": 191,
		"topic": "",
		"metric": "Number of employees",
		"units": "number",
		"sasb_code": "RT-EE-000.B",
		"gri_code": "<span class='opacity-40'>-</span>",
		"eic": "<span class='opacity-40'>-</span>",
	},
];

const note_a =
	"Version 2018-10: Version 2018-10: SASB Extractives & Minerals Processing Sector Oil & Gas Midstream Standard EM-MD, SASB Extractives & Minerals Processing Sector Exploration & Production Standard EM-EP, SASB Resource Transformation Sector - Chemicals RT-CH, SASB Resource Transformation Sector - Electrical & Electronic Equipment Standard RT-EE, and SASB Consumer Goods Sector - E-Commerce Standard CG-EC.";

const note_b =
	"GRI 11: Oil and Gas Sector 2021, GRI 3: Material Topics 2021, GRI 302: Energy 2016, GRI 304: Biodiversity 2016, GRI 305: emissions 2016, GRI 306: Waste 2020, GRI 401: Employment 2016, GRI 403: Occupational Health and Safety 2018, and GRI 405: Diversity and Equal Opportunity 2016.";

const note_c =
	"EIC/GPA Midstream ESG Reporting Template Metric developed by the Energy Infrastructure Council in collaboration with GPA Midstream.";

const note_1 =
	"Throughput was converted to MMBtu using product-specific heat content, obtained from the EIA, EPA, or business specific data.  This is then converted to BOE by dividing by 5.8 MMBtu per barrel of crude oil.";

const note_2 =
	"Scope 3 categories include business travel (Scope 3, Category 6) and employee commuting (Scope 3, Category 7).";

const note_3 =
	"An out-of-service pipeline was removed from a wetlands area in partnership with the Huntington Beach Wetlands Conservancy.  The entire project area is being restored to become a fully functioning wetlands area.";

export const contentIndex2021 = readable({
	data: array,
	headings: [
		headings[0],
		headings[1],
		headings[2],
		headings[3],
		headings[4],
		headings[5],
		headings[6],
		headings[7],
		headings[8],
	],
	keys: [
		"topic",
		"metric",
		"units",
		"2019",
		"2020",
		"2021",
		"sasb_code",
		"gri_code",
		"eic",
	],
	notes: [
		["a", note_a],
		["b", note_b],
		["c", note_c],
		["1", note_1],
		["2", note_2],
		["3", note_3],
	],
});
